### PR TITLE
Remove unnecessary read permission request when picking files

### PR DESCRIPTION
**Pull request by dknchris**
Is read permission really needed when picking files via SAF? Files picked by the user through SAF will be readable anyway by the requesting app.

PS: Github diff view in this commit is garbage.

### CODE REVIEW

**Comment by anggrayudi** [comment]
Can you help to remove function `onStoragePermissionDenied()` in file picker callback as well?

**Comment by dknchris** [comment]
Done. Should be good to go now. Do let me know if you need any other changes.

**Comment by anggrayudi** [comment]
Can you fix the compile error?

**Comment by anggrayudi** [comment]
Great! Thanks for your effort.

**Comment by dknchris** [comment]
No problem, your work is much appreciated. Thanks!

**Pull request merged**
